services:
  postgres:
    image: postgres:18
    container_name: atm-postgres
    environment:
      POSTGRES_DB: atm_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin
    ports:
      - "5432:5432"
    volumes:
      - atm_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d atm_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: atm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  atm_postgres_data: